import { Button } from "@/components/ui/button";
import { seo } from "@/lib/seo";
import { createFileRoute } from "@tanstack/react-router"; import { useState,type FormEvent } from "react"; import { z } from "zod"; import { Clock3, MapPin, MessageCircle, Phone, Mail } from "lucide-react"; import { SiteShell } from "@/components/site/SiteShell"; import { PageHero } from "@/components/site/PageHero"; const hero = "/img/r3-equipe-1200.webp"; import { ADDRESS,PHONE_DISPLAY,PHONE_SECONDARY,QUOTE_EMAIL,WHATSAPP } from "@/lib/r3";
const desc="Solicite um orçamento para usinagem de campo, soldagem, caldeiraria ou manutenção industrial com a R3 Usinagem.";
export const Route=createFileRoute("/contato")({head:()=>seo({path:"/contato",title:"Orçamento de Usinagem em Cubatão/SP | Contato R3 Usinagem",description:"Peça orçamento de usinagem em Cubatão e Baixada Santista. WhatsApp (13) 99707-6274, Rua Pedro de Toledo, 179. Orçamento em média em 1 a 2 dias úteis.",crumbs:[{name:"Contato",path:"/contato"}]}),component:Page});
const schema=z.object({nome:z.string().trim().min(2,"Informe seu nome.").max(100),empresa:z.string().trim().max(120),telefone:z.string().trim().min(8,"Informe um telefone válido.").max(30),email:z.string().trim().email("Informe um e-mail válido.").max(255),cidade:z.string().trim().min(2,"Informe cidade e estado.").max(100),servico:z.string().min(1,"Selecione um serviço."),mensagem:z.string().trim().min(10,"Conte um pouco mais sobre a necessidade.").max(1200)});
function Page(){const [error,setError]=useState("");const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setError("");const f=new FormData(e.currentTarget);const data={nome:String(f.get("nome")||""),empresa:String(f.get("empresa")||""),telefone:String(f.get("telefone")||""),email:String(f.get("email")||""),cidade:String(f.get("cidade")||""),servico:String(f.get("servico")||""),mensagem:String(f.get("mensagem")||"")};const parsed=schema.safeParse(data);if(!parsed.success){setError(parsed.error.issues[0]?.message||"Revise os dados informados.");return}const text=["Olá, gostaria de solicitar um orçamento.",`Nome: ${data.nome}`,`Empresa: ${data.empresa||"Não informada"}`,`Telefone: ${data.telefone}`,`E-mail: ${data.email}`,`Cidade/Estado: ${data.cidade}`,`Serviço: ${data.servico}`,`Mensagem: ${data.mensagem}`].join("\n");const action=(e.nativeEvent as SubmitEvent).submitter;
if(action instanceof HTMLButtonElement && action.value==="email"){
window.location.href=`mailto:${QUOTE_EMAIL}?subject=${encodeURIComponent(`Solicitação de orçamento — ${parsed.data.servico}`)}&body=${encodeURIComponent(text)}`;
}else{window.open(`https://wa.me/${WHATSAPP}?text=${encodeURIComponent(text)}`,"_blank","noopener,noreferrer")}};return <SiteShell><PageHero eyebrow="Contato" title="Vamos falar sobre o seu projeto?" subtitle="Envie as informações da sua necessidade e entre em contato com a R3 Usinagem." image={hero} breadcrumb={[{label:"Home",to:"/"},{label:"Contato"}]}/><section className="section"><div className="container-x grid gap-10 lg:grid-cols-[1.25fr_.75fr]"><form onSubmit={submit} className="grid gap-5 border-t-4 border-brand bg-mist p-6 sm:p-9" noValidate><div><span className="eyebrow">Orçamento</span><h2 className="mt-4 text-4xl">Conte o que sua operação precisa.</h2></div><div className="grid gap-5 sm:grid-cols-2"><Field label="Nome" name="nome" required/><Field label="Empresa" name="empresa"/><Field label="Telefone / WhatsApp" name="telefone" type="tel" required/><Field label="E-mail" name="email" type="email" required/><Field label="Cidade / Estado" name="cidade" required/><label><Label>Serviço de interesse *</Label><select name="servico" required className="input-style" defaultValue=""><option value="" disabled>Selecione</option>{["Usinagem de Campo","Usinagem de Base","Serviços de Solda","Caldeiraria","Manutenção Industrial","Outro"].map(x=><option key={x}>{x}</option>)}</select></label></div><label><Label>Mensagem *</Label><textarea name="mensagem" rows={5} required maxLength={1200} className="input-style resize-none"/></label>{error&&<p role="alert" className="border-l-2 border-brand pl-3 text-sm font-semibold text-carbon">{error}</p>}<div className="grid gap-3 sm:grid-cols-2"><Button type="submit" name="canal" value="email" variant="outline" className="btn-base btn-outline-brand h-auto whitespace-normal"><Mail className="h-4 w-4"/>Solicitar via email</Button><Button type="submit" name="canal" value="whatsapp" className="btn-base btn-primary h-auto whitespace-normal"><MessageCircle className="h-4 w-4"/>Solicitar via WhatsApp</Button></div></form><aside className="space-y-4"><Info Icon={Phone} title="Telefones"><a href="tel:+5513997076274" className="block hover:text-brand">{PHONE_DISPLAY}</a><a href="tel:+5513988355067" className="block hover:text-brand">{PHONE_SECONDARY}</a><span className="mt-2 block text-xs text-steel">Telefone ativo 24 horas para dúvidas e contatos.</span></Info><Info Icon={Mail} title="Email"><a href={`mailto:${QUOTE_EMAIL}`} className="break-all hover:text-brand">{QUOTE_EMAIL}</a></Info><Info Icon={MapPin} title="Endereço">{ADDRESS}</Info><Info Icon={Clock3} title="Horário">Segunda a quinta: 07:00–17:00<br/>Sexta: 07:00–16:00<br/>Sábado e domingo: fechado</Info></aside></div></section><section className="bg-mist pb-20"><div className="container-x"><MapEmbed/></div></section></SiteShell>}
function Label({children}:{children:React.ReactNode}){return <span className="mb-2 block text-[.68rem] font-bold uppercase tracking-[.1em] text-graphite">{children}</span>} function Field({label,name,type="text",required=false}:{label:string;name:string;type?:string;required?:boolean}){return <label><Label>{label}{required?" *":""}</Label><input name={name} type={type} required={required} maxLength={type==="email"?255:120} className="input-style"/></label>} function Info({Icon,title,children}:{Icon:React.ComponentType<{className?:string}>;title:string;children:React.ReactNode}){return <div className="border border-border p-6"><Icon className="h-7 w-7 text-brand"/><h3 className="mt-4 text-2xl">{title}</h3><div className="mt-3 text-sm leading-7 text-graphite">{children}</div></div>}

function MapEmbed(){const [on,setOn]=useState(false);return on?<iframe title="Mapa da R3 Usinagem em Cubatão" src="https://www.google.com/maps?q=Rua+Pedro+de+Toledo+179+Vila+Paulista+Cubat%C3%A3o+SP+11510-090&output=embed" loading="lazy" className="h-[420px] w-full border-0"/>:<button type="button" onClick={()=>setOn(true)} className="flex h-[420px] w-full flex-col items-center justify-center gap-3 border border-steel/40 bg-carbon text-center text-white"><MapPin className="h-8 w-8 text-brand"/><span className="font-display text-xl font-semibold">Ver mapa da R3 Usinagem</span><span className="text-sm opacity-80">Rua Pedro de Toledo, 179 — Vila Paulista — Cubatão/SP</span></button>}
